name: Trigger auto deployment for container-app-oq5ad42mnikkg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-oq5ad42mnikkg-AutoDeployTrigger-9a698b65-07b4-4c2a-9cef-94e2be8ec86e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOQ5AD42MNIKKG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOQ5AD42MNIKKG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOQ5AD42MNIKKG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOQ5AD42MNIKKG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOQ5AD42MNIKKG_REGISTRY_PASSWORD }}
          containerAppName: container-app-oq5ad42mnikkg
          resourceGroup: todonodejspgsqlgoogleauth95d59cdd
          imageToBuild: default/container-app-oq5ad42mnikkg:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


